//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "api_keys")]
pub struct Model {
    pub service_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub key_id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", unique)]
    pub key: Vec<u8>,
    pub last_used: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_key_scopes::Entity")]
    ApiKeyScopes,
    #[sea_orm(
        belongs_to = "super::services::Entity",
        from = "Column::ServiceId",
        to = "super::services::Column::ServiceId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Services,
}

impl Related<super::api_key_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeyScopes.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
