//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group_subscribers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub service_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_id: Uuid,
    pub subscriber_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::groups::Entity",
        from = "(Column::ServiceId, Column::GroupId)",
        to = "(super::groups::Column::ServiceId, super::groups::Column::GroupId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Groups,
    #[sea_orm(
        belongs_to = "super::subscribers::Entity",
        from = "(Column::ServiceId, Column::SubscriberId)",
        to = "(super::subscribers::Column::ServiceId, super::subscribers::Column::SubscriberId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Subscribers,
}

impl Related<super::groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groups.def()
    }
}

impl Related<super::subscribers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subscribers.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        super::subscribers::Relation::Services.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::subscribers::Relation::GroupSubscribers.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
